import type { UnitData } from '../types/unit'

export const initialEnemyUnits: UnitData[] = [
  {
    id: 'enemy-unit-rho',
    team: 'enemy',
    position: [-1.8, 0, -7.2],
    moveSpeed: 0,
    stopDistance: 0.12,
    maxHealth: 100,
    currentHealth: 100,
    attackRange: 2.35,
    attackDamage: 12,
    attackCooldown: 0.75,
    attackCooldownRemaining: 0,
  },
  {
    id: 'enemy-unit-sigma',
    team: 'enemy',
    position: [0, 0, -6.6],
    moveSpeed: 0,
    stopDistance: 0.12,
    maxHealth: 100,
    currentHealth: 100,
    attackRange: 2.35,
    attackDamage: 12,
    attackCooldown: 0.75,
    attackCooldownRemaining: 0,
  },
  {
    id: 'enemy-unit-tau',
    team: 'enemy',
    position: [1.8, 0, -7.2],
    moveSpeed: 0,
    stopDistance: 0.12,
    maxHealth: 100,
    currentHealth: 100,
    attackRange: 2.35,
    attackDamage: 12,
    attackCooldown: 0.75,
    attackCooldownRemaining: 0,
  },
]
